Libs =

Build: ./main.cpp
	echo "Building...\n"
	g++ ${Libs} ./main.cpp -o ./main.out
	echo "Ready"

Run: Build
	echo "start run"
	./main.out

RunTime: Build
	echo "start run on time"
	time ./main.out